### ISSUE TITLE
Update Text In Nyingma Logos

### ISSUE THREAD

**Issue by 5HT** [5HT/nying.ma#56]
1. Long version: left སྔ་འགྱུར་རྙིང་མའིི་ right  བསྟན་པའི་འབྱུང་གནས་ center རྒྱལ་བ་ཀཿཐོག་རྡོ་རྗེའི་གདན།
2. Short version: left སྔ་འགྱུར་ right  རྙིང་མ་ center ཀཿཐོག་རྡོ་རྗེའི་གདན།

**Comment by Azenberg** [comment]
okay!

**Comment by 5HT** [comment]
https://github.com/5HT/nying.ma/blob/gh-pages/images/nyingma.png

**Comment by pemadudul** [comment]
В правом квадрате пропущена конечная точка

2015-08-06 6:00 GMT+05:45 Namdak Tonpa notifications@github.com:

> Closed #56 https://github.com/5HT/nying.ma/issues/56.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/5HT/nying.ma/issues/56#event-374802031.

## 

With best regards,
Sergey Dudko
